# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarFlavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('images', models.ImageField(blank=True, default='', upload_to='star/photos', verbose_name='фотография')),
            ],
            options={
                'verbose_name': 'Звездный букет',
                'verbose_name_plural': 'Звездная коллекция',
                'ordering': ['name'],
            },
        ),
    ]
