# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-27 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albome', '0003_auto_20170527_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='название'),
        ),
    ]
